# Prepare Data for Experiments

In [ ]:
# Authenticate with Google Cloud to access services like BigQuery.
from google.colab import auth
auth.authenticate_user()

# Import the BigQuery client library.
from google.cloud import bigquery
# Initialize a BigQuery client with your project ID.
client = bigquery.Client(project="rl-semester-project")


# Review the Schema for Google Cluster Data

In [ ]:

# Define the public project, dataset, and table to query.
public_proj = "google.com:google-cluster-data"
dataset     = "clusterdata_2019_h"
table       = "instance_usage"

# SQL query to retrieve schema information for the 'instance_usage' table
schema_df = client.query(f"""
SELECT
  column_name,  -- Select the column name
  data_type     -- Select the data type of the column
FROM `{public_proj}.{dataset}.INFORMATION_SCHEMA.COLUMNS`
WHERE table_name = '{table}' -- Filter for the specified table
ORDER BY ordinal_position   -- Order by the position of the column in the table
""").to_dataframe()

# Display the schema information in a DataFrame.
schema_df

                        column_name                             data_type
0                        start_time                                 INT64
1                          end_time                                 INT64
2                     collection_id                                 INT64
3                    instance_index                                 INT64
4                        machine_id                                 INT64
5               alloc_collection_id                                 INT64
6              alloc_instance_index                                 INT64
7                   collection_type                                 INT64
8                     average_usage  STRUCT<cpus FLOAT64, memory FLOAT64>
9                     maximum_usage  STRUCT<cpus FLOAT64, memory FLOAT64>
10              random_sample_usage  STRUCT<cpus FLOAT64, memory FLOAT64>
11                  assigned_memory                               FLOAT64
12                page_cache_memory                               FLOAT64
13           cycles_per_instruction                               FLOAT64
14  memory_accesses_per_instruction                               FLOAT64
15                      sample_rate                               FLOAT64
16           cpu_usage_distribution                        ARRAY<FLOAT64>
17      tail_cpu_usage_distribution                        ARRAY<FLOAT64>

# Data Pre-Processing:
### Aggregate CPU and memory load from instance_usage:

In [ ]:
# Authenticate with Google Cloud to access services like BigQuery.
from google.colab import auth
auth.authenticate_user()

# Import the BigQuery client library.
from google.cloud import bigquery
# Initialize a BigQuery client with your project ID.
client = bigquery.Client(project="rl-semester-project")

records_limit = 100  # Define the number of records to download, further reduced due to persistent quota issue

# SQL query to aggregate CPU and memory usage from the 'instance_usage' table
sql = f"""
SELECT
  # Truncate the start time to the minute to create time windows
  TIMESTAMP_TRUNC(TIMESTAMP_MICROS(start_time), MINUTE) AS time_window,
  # Calculate the average CPU usage for each time window
  AVG(average_usage.cpus) AS avg_cpu,
  # Calculate the average memory usage for each time window
  AVG(average_usage.memory) AS avg_mem,
  # Count the number of distinct machines active in each time window
  COUNT(DISTINCT machine_id) AS active_machines
FROM `google.com:google-cluster-data.clusterdata_2019_a.instance_usage`
# Group the results by the time window
GROUP BY time_window
# Order the results by the time window
ORDER BY time_window
# Limit the results to the specified number of rows
LIMIT {records_limit}
"""
# Execute the BigQuery query and load the results into a pandas DataFrame
df_usage = client.query(sql).to_dataframe()
# Display the first few rows of the DataFrame
df_usage.head()

Forbidden: 403 Quota exceeded: Your project exceeded quota for free query bytes scanned. For more information, see https://cloud.google.com/bigquery/docs/troubleshoot-quotas; reason: quotaExceeded, location: unbilled.analysis, message: Quota exceeded: Your project exceeded quota for free query bytes scanned. For more information, see https://cloud.google.com/bigquery/docs/troubleshoot-quotas

Location: US
Job ID: b8f4f590-54be-4f80-bd3c-351eae9433c5

In [ ]:
# Inspect the shape of the DataFrame (number of rows and columns)
print(df_usage.shape)
# Print the list of column names
print(df_usage.columns.tolist())
# Display the first 3 rows of the DataFrame to get a preview of the data
df_usage.head(3)

(10000, 4)
['time_window', 'avg_cpu', 'avg_mem', 'active_machines']

                time_window   avg_cpu   avg_mem  active_machines
0 1970-01-01 00:05:00+00:00  0.006623  0.004912             9525
1 1970-01-01 00:06:00+00:00  0.003254  0.002733             3805
2 1970-01-01 00:07:00+00:00  0.003070  0.002770             4167

In [ ]:
#Make sure the time series is in order, since RL transitions depend on consecutive steps:
df_usage = df_usage.sort_values("time_window").reset_index(drop=True)
df_usage.head(3)

                time_window   avg_cpu   avg_mem  active_machines
0 1970-01-01 00:05:00+00:00  0.006623  0.004912             9525
1 1970-01-01 00:06:00+00:00  0.003254  0.002733             3805
2 1970-01-01 00:07:00+00:00  0.003070  0.002770             4167